### ISSUE TITLE
Flashing of header when clicking mmenu humburger

### ISSUE THREAD

**Issue by otterslide** [FrDH/mhead-js#2]
When clicking on the hamburger at this url:
https://mmenujs.com/documentation/addons/navbars.html
The header with "Introduction Examples ... " disappears and re-appears quickly when the menu is opening.
When it closes it doesn't do this. My colors are darker and it's much more noticeable.

Any way this can be fixed?.. I'm assuming some styles are being applied that make the header disappear and then again to make it appear.
perhaps they can be applied in a different order to eliminate this flash? 
Thanks!

**Comment by otterslide** [comment]
I used the performance recorder in Chrome and yes, the entire header disappears for a few ms and then re-appears.  In Firefox I don't even notice it at all, but in Chrome it's quite noticeable.
Without the fixed elements extension JS when opening the menu the entire header disappears. I'm assuming that for some reason the header is getting hidden by the opening action and then it's being re-displayed by the extension?

**Comment by FrDH** [comment]
Thank you for reporting this and sorry for the late reply.
This is due to the few ms the mmenu plugin needs between showing the menu and actually opening the menu. I'll see if I can get it fixed.

**Comment by markustobler** [comment]
Could you fix that issue? I have the same problem here.
