### ISSUE TITLE
unpin option ignores given value

### ISSUE THREAD

**Issue by magic-77** [FrDH/mhead-js#7]
Whatever value i use for the "unpin" option, the result is always the same. Header is being unpined at a specific position.

This has the same result
```
new Mhead('#page__header', {
 scroll: {
      unpin: 1500
  }
});
```
as when setting the value to
```
new Mhead('#page__header', {
 scroll: {
      unpin: 200
  }
});
```
So what i'm missing here. I need to unpin the Header later

**Comment by FrDH** [comment]
What version are you using?
The plugin got slimmed down and the pin and unpin options no longer reside in the scroll object.
Try it like this:

````js
new Mhead('#page__header', {
      unpin: 200
});
````

**Comment by magic-77** [comment]
@FrDH I'm using the latest Version.
Removing the "scroll" Object gives me the Result i need to pin / unpin Header.
Thank you :-)
