### ISSUE TITLE
CSS missing (from 1.0.1 to 2.x)

### ISSUE THREAD

**Issue by huelsmc** [FrDH/mhead-js#8]
Hi,

we currently are trying to update mhead (and mmenu) to the latest version.
However it seems especially mhead has some missing stuff since the update to 2.

The whole css seems to be missing and if I compare the previous versions classes with the classes of the new version it is not enough to just keep the original jquery.mhead.css file since the required classes for styling aren't included anymore.
e.g. (in the main div of mhead):
`mh-btns-left mh-btns-right-3`

**Comment by FrDH** [comment]
Version 2 was stripped from a lot of styling as it was out of scope for the plugin.

**Comment by huelsmc** [comment]
Ok so only way to keep that without having to rewrite all that rules is to stay on the older versions? Or differently: Are there any plans to bring these features back?

**Comment by FrDH** [comment]
There are no plans to bring those feature back.
If you want, you could copy/paste the needed css from the old version.

**Comment by huelsmc** [comment]
For others that run into this:

You need somehow to integrate the proper class for the amount of buttons since this feature seems to have been removed as well. Maybe at least this can be brought back else it's nearly impossible to syle the head properly in case that the amount of buttons is dynamic.

For everything else this can be closed.
